### ISSUE TITLE
Sass Ruby Gem is being deprecated

### ISSUE THREAD

**Issue by ghost** [FoxinouFR/scss-onsave#1]
Hey,

The Sass Ruby Gem is being deprecated (fully unmaintained from 26 March) and now shows a deprecation message whenever you install it. Is it possible to have this dependency replaced with the Node package, or does this specifically require that Ruby gem?

**Comment by FoxinouFR** [comment]
Hello,
Thanks for the info!
I made the necessary changes (version 0.3.0) to make everything work with the NPM command while keeping the possibility for those still using Ruby to use the package.
Have a good day!

**Comment by ghost** [comment]
Great, thanks :)
